.TH "src/PaymentPlan.php" 3 "Wed Nov 11 2020" "Flutterwave SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/PaymentPlan.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBPaymentPlan\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBKuzalab\fP"
.br
.ti -1c
.RI " \fBPhelix\\Flutterwave\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Flutterwave SDK from the source code\&.
