.TH "PaymentOption" 3 "Wed Nov 11 2020" "Flutterwave SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaymentOption
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBACCOUNT\fP = 'account'"
.br
.ti -1c
.RI "const \fBCARD\fP = 'card'"
.br
.ti -1c
.RI "const \fBBANK_TRANSFER\fP = 'banktransfer'"
.br
.ti -1c
.RI "const \fBMPESA\fP = 'mpesa'"
.br
.ti -1c
.RI "const \fBMOBILE_MONEY_RWANDA\fP = 'mobilemoneyrwanda'"
.br
.ti -1c
.RI "const \fBMOBILE_MONEY_ZAMBIA\fP = 'mobilemoneyzambia'"
.br
.ti -1c
.RI "const \fBMOBILE_MONEY_UGANDA\fP = 'mobilemoneyuganda'"
.br
.ti -1c
.RI "const \fBMOBILE_MONEY_GHANA\fP = 'mobilemoneyghana'"
.br
.ti -1c
.RI "const \fBMOBILE_MONEY_FRANCO\fP = 'mobilemoneyfranco'"
.br
.ti -1c
.RI "const \fBMOBILE_MONEY_TANZANIA\fP = 'mobilemoneytanzania'"
.br
.ti -1c
.RI "const \fBQR\fP = 'qr'"
.br
.ti -1c
.RI "const \fBUSSD\fP = 'ussd'"
.br
.ti -1c
.RI "const \fBCREDIT\fP = 'credit'"
.br
.ti -1c
.RI "const \fBBARTER\fP = 'barter'"
.br
.ti -1c
.RI "const \fBPAGA\fP = 'paga'"
.br
.ti -1c
.RI "const \fBVOUCHER\fP = '1voucher'"
.br
.ti -1c
.RI "const \fBPAY_ATTITUDE\fP = 'payattitude'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file PaymentOption\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const ACCOUNT = 'account'"

.PP
Definition at line 16 of file PaymentOption\&.php\&.
.SS "const BANK_TRANSFER = 'banktransfer'"

.PP
Definition at line 18 of file PaymentOption\&.php\&.
.SS "const BARTER = 'barter'"

.PP
Definition at line 29 of file PaymentOption\&.php\&.
.SS "const CARD = 'card'"

.PP
Definition at line 17 of file PaymentOption\&.php\&.
.SS "const CREDIT = 'credit'"

.PP
Definition at line 28 of file PaymentOption\&.php\&.
.SS "const MOBILE_MONEY_FRANCO = 'mobilemoneyfranco'"

.PP
Definition at line 24 of file PaymentOption\&.php\&.
.SS "const MOBILE_MONEY_GHANA = 'mobilemoneyghana'"

.PP
Definition at line 23 of file PaymentOption\&.php\&.
.SS "const MOBILE_MONEY_RWANDA = 'mobilemoneyrwanda'"

.PP
Definition at line 20 of file PaymentOption\&.php\&.
.SS "const MOBILE_MONEY_TANZANIA = 'mobilemoneytanzania'"

.PP
Definition at line 25 of file PaymentOption\&.php\&.
.SS "const MOBILE_MONEY_UGANDA = 'mobilemoneyuganda'"

.PP
Definition at line 22 of file PaymentOption\&.php\&.
.SS "const MOBILE_MONEY_ZAMBIA = 'mobilemoneyzambia'"

.PP
Definition at line 21 of file PaymentOption\&.php\&.
.SS "const MPESA = 'mpesa'"

.PP
Definition at line 19 of file PaymentOption\&.php\&.
.SS "const PAGA = 'paga'"

.PP
Definition at line 30 of file PaymentOption\&.php\&.
.SS "const PAY_ATTITUDE = 'payattitude'"

.PP
Definition at line 32 of file PaymentOption\&.php\&.
.SS "const QR = 'qr'"

.PP
Definition at line 26 of file PaymentOption\&.php\&.
.SS "const USSD = 'ussd'"

.PP
Definition at line 27 of file PaymentOption\&.php\&.
.SS "const VOUCHER = '1voucher'"

.PP
Definition at line 31 of file PaymentOption\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Flutterwave SDK from the source code\&.
