.TH "FlutterwaveException" 3 "Wed Nov 11 2020" "Flutterwave SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlutterwaveException
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($message, $code=0, Exception $previous=null)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file FlutterwaveException\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $message,  $code = \fC0\fP, Exception $previous = \fCnull\fP)"
Redefine the exception so message isn't optional SDPException constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fI$message\fP 
.br
\fI$code\fP 
.br
\fI$previous\fP 
.RE
.PP

.PP
Definition at line 23 of file FlutterwaveException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Flutterwave SDK from the source code\&.
