.TH "Verification" 3 "Wed Nov 11 2020" "Flutterwave SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Verification
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBFlutterwave\fP $flutterwave)"
.br
.ti -1c
.RI "\fBverify\fP ($transactionId, $transactionReference, $currency, $amount)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$flutterwave\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file Verification\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBFlutterwave\fP $flutterwave)"
\fBVerification\fP constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fI$flutterwave\fP 
.RE
.PP

.PP
Definition at line 27 of file Verification\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "verify ( $transactionId,  $transactionReference,  $currency,  $amount)"
Verify a transaction Uses transaction reference, currency and amount to verify the transaction
.PP
\fBParameters\fP
.RS 4
\fI$transactionId\fP 
.br
\fI$transactionReference\fP 
.br
\fI$currency\fP 
.br
\fI$amount\fP 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 41 of file Verification\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$flutterwave\fC [protected]\fP"

.PP
Definition at line 21 of file Verification\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Flutterwave SDK from the source code\&.
