.TH "Request" 3 "Wed Nov 11 2020" "Flutterwave SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Request
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($baseURI)"
.br
.ti -1c
.RI "\fBrequest\fP ($method, $uri, $token=null, $body=null, $query_params=null)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$client\fP"
.br
.ti -1c
.RI "\fB$success\fP = false"
.br
.ti -1c
.RI "\fB$statusCode\fP"
.br
.ti -1c
.RI "\fB$statusText\fP"
.br
.ti -1c
.RI "\fB$responseBody\fP"
.br
.ti -1c
.RI "\fB$responseMessage\fP"
.br
.ti -1c
.RI "\fB$responseData\fP"
.br
.ti -1c
.RI "\fB$debugRequestTrace\fP"
.br
.ti -1c
.RI "\fB$debugResponseTrace\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file Request\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $baseURI)"
\fBRequest\fP constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fI$baseURI\fP 
.RE
.PP

.PP
Definition at line 46 of file Request\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "request ( $method,  $uri,  $token = \fCnull\fP,  $body = \fCnull\fP,  $query_params = \fCnull\fP)"
Make a http request
.PP
\fBParameters\fP
.RS 4
\fI$method\fP 
.br
\fI$uri\fP 
.br
\fI$token\fP 
.br
\fI$body\fP 
.br
\fI$query_params\fP 
.RE
.PP
\fBReturns\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 60 of file Request\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$client"

.PP
Definition at line 20 of file Request\&.php\&.
.SS "$debugRequestTrace"

.PP
Definition at line 39 of file Request\&.php\&.
.SS "$debugResponseTrace"

.PP
Definition at line 40 of file Request\&.php\&.
.SS "$responseBody"

.PP
Definition at line 33 of file Request\&.php\&.
.SS "$responseData"

.PP
Definition at line 37 of file Request\&.php\&.
.SS "$responseMessage"

.PP
Definition at line 35 of file Request\&.php\&.
.SS "$statusCode"

.PP
Definition at line 29 of file Request\&.php\&.
.SS "$statusText"

.PP
Definition at line 31 of file Request\&.php\&.
.SS "$success = false"

.PP
Definition at line 27 of file Request\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Flutterwave SDK from the source code\&.
