.TH "Account" 3 "Wed Nov 11 2020" "Flutterwave SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Account
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBFlutterwave\fP $flutterwave)"
.br
.ti -1c
.RI "\fBgetAllBalances\fP ()"
.br
.ti -1c
.RI "\fBgetAccountBalance\fP ($currency)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$flutterwave\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file Account\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBFlutterwave\fP $flutterwave)"
\fBAccount\fP constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fI$flutterwave\fP 
.RE
.PP

.PP
Definition at line 26 of file Account\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getAccountBalance ( $currency)"
Get balance of a specific account identified by the specified currency
.PP
\fBParameters\fP
.RS 4
\fI$currency\fP 
.RE
.PP
\fBReturns\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 49 of file Account\&.php\&.
.SS "getAllBalances ()"
Get all balances Gets all balances for each of the currencies
.PP
\fBReturns\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 36 of file Account\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$flutterwave\fC [protected]\fP"

.PP
Definition at line 20 of file Account\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Flutterwave SDK from the source code\&.
