.TH "Flutterwave" 3 "Wed Nov 11 2020" "Flutterwave SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Flutterwave
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($secretKey, $encryptionKey=null, $publicKey=null, $debugLevel=null)"
.br
.ti -1c
.RI "\fBinit\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$encryptionKey\fP"
.br
.ti -1c
.RI "\fB$debugLevel\fP"
.br
.ti -1c
.RI "\fB$token\fP"
.br
.ti -1c
.RI "\fB$request\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main application class\&. 
.PP
Definition at line 20 of file Flutterwave\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $secretKey,  $encryptionKey = \fCnull\fP,  $publicKey = \fCnull\fP,  $debugLevel = \fCnull\fP)"
\fBFlutterwave\fP constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fI$secretKey\fP 
.br
\fI$encryptionKey\fP 
.br
\fI$publicKey\fP 
.br
\fI$debugLevel\fP 
.RE
.PP

.PP
Definition at line 77 of file Flutterwave\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "init ()"

.PP
\fBReturns\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 90 of file Flutterwave\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$debugLevel"
Holds the debug level 
.PP
Definition at line 56 of file Flutterwave\&.php\&.
.SS "integer $encryptionKey"
Encryption key from fullterwave account 
.PP
Definition at line 50 of file Flutterwave\&.php\&.
.SS "\fBRequest\fP $request"

.PP
Definition at line 67 of file Flutterwave\&.php\&.
.SS "string $token"
Bearer token to use for all requests 
.PP
Definition at line 62 of file Flutterwave\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Flutterwave SDK from the source code\&.
