.TH "Phelix\Flutterwave" 3 "Wed Nov 11 2020" "Flutterwave SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Phelix\Flutterwave
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBExceptions\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAccount\fP"
.br
.ti -1c
.RI "class \fBFlutterwave\fP"
.br
.ti -1c
.RI "class \fBOTP\fP"
.br
.ti -1c
.RI "class \fBPaymentOption\fP"
.br
.ti -1c
.RI "class \fBPaymentPlan\fP"
.br
.ti -1c
.RI "class \fBRequest\fP"
.br
.ti -1c
.RI "class \fBSettlement\fP"
.br
.ti -1c
.RI "class \fBStandard\fP"
.br
.ti -1c
.RI "class \fBSubscription\fP"
.br
.ti -1c
.RI "class \fBUtils\fP"
.br
.ti -1c
.RI "class \fBVerification\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Flutterwave SDK from the source code\&.
