.TH "Utils" 3 "Wed Nov 11 2020" "Flutterwave SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetCallbackResponseDataItemValue\fP ($responseData, $item)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file Utils\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static getCallbackResponseDataItemValue ( $responseData,  $item)\fC [static]\fP"
Get SDP callback data from an array 
.PP
\fBParameters\fP
.RS 4
\fI$responseData\fP 
.br
\fI$item\fP 
.RE
.PP
\fBReturns\fP
.RS 4
mixed|string 
.RE
.PP

.PP
Definition at line 55 of file Utils\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Flutterwave SDK from the source code\&.
